# Generated by Django 3.2.15 on 2023-12-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modbus_signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=64)),
                ('address', models.IntegerField()),
                ('ctime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': '设备测点',
                'verbose_name_plural': '设备测点',
            },
        ),
    ]
