# Generated by Django 3.2.15 on 2023-12-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='machine_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=64)),
                ('val', models.IntegerField()),
                ('ctime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PM设备数据',
                'verbose_name_plural': 'PM设备数据',
            },
        ),
        migrations.CreateModel(
            name='pm_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32)),
                ('machine', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=64)),
                ('detail', models.CharField(max_length=256)),
                ('frequency', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('ctime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PM内容',
                'verbose_name_plural': 'PM内容',
            },
        ),
        migrations.CreateModel(
            name='pm_finish_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32)),
                ('machine', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=64)),
                ('detail', models.CharField(default='', max_length=256)),
                ('frequency', models.IntegerField(default=0)),
                ('type', models.CharField(default='T', max_length=32)),
                ('val_last', models.IntegerField(default=0)),
                ('val_current', models.IntegerField(default=0)),
                ('time_last', models.DateField()),
                ('life', models.IntegerField(default=0)),
                ('push', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
                ('user', models.CharField(max_length=32)),
                ('ctime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PM完成记录',
                'verbose_name_plural': 'PM完成记录',
            },
        ),
        migrations.CreateModel(
            name='pm_modify_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32)),
                ('machine', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=64)),
                ('detail', models.CharField(max_length=256)),
                ('frequency', models.IntegerField()),
                ('type', models.CharField(max_length=32)),
                ('user', models.CharField(max_length=256)),
                ('notes', models.CharField(max_length=256)),
                ('ctime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PM修改记录',
                'verbose_name_plural': 'PM修改记录',
            },
        ),
        migrations.CreateModel(
            name='pm_push',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=32)),
                ('machine', models.CharField(max_length=32)),
                ('station', models.CharField(max_length=32)),
                ('item', models.CharField(max_length=64)),
                ('detail', models.CharField(default='', max_length=256)),
                ('frequency', models.IntegerField(default=0)),
                ('type', models.CharField(default='T', max_length=32)),
                ('val_last', models.IntegerField(default=0)),
                ('val_current', models.IntegerField(default=0)),
                ('time_last', models.DateField()),
                ('life', models.IntegerField(default=0)),
                ('push', models.IntegerField(default=0)),
                ('done', models.IntegerField(default=0)),
                ('ctime', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PM推送数据',
                'verbose_name_plural': 'PM推送数据',
            },
        ),
    ]
